console.log("---------------1--------------");
var sweety="Sweety"
var cutie="Cutie";
console.log("Before Swapping Value = ");
console.log("sweety = ",sweety);
console.log("cutie  = ",cutie);
var temp;
temp=sweety;
sweety=cutie;
cutie=temp;
console.log("After Swapping Value = ");
console.log("sweety = ",sweety);
console.log("Cutie  = ",cutie);
console.log("---------------2--------------");
var num1=100;
var num2=200;
var num3=300;
console.log("Before Swapping Three Variable Values = ");
console.log("num1 = ",num1);
console.log("num2 = ",num2);
console.log("num3 = ",num3 ); 
var temp;
temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log("After Swapping Three Variable Value = ");
console.log("num1=",num1);
console.log("num2=",num2);
console.log("num3=",num3);
