console.log(`Assignment 01:For a given array fruits perform below operations as:`);
const arrayFruits=["Banana","Orange","Apple","Mango","Water Melon"];
arrayFruits[0];
arrayFruits[arrayFruits.length-1];
console.log(`1.First element is: ${arrayFruits[0]}`);
console.log(`2.Last  element is:${arrayFruits[arrayFruits.length-1]}`);
console.log(``);
console.log(`2.Add elements are:`);
var char=arrayFruits.unshift("Papaya");
console.log(arrayFruits);
console.log(``);
console.log(`3.Remove 'Mango' from the array:`);
arrayFruits.splice(4,1);
console.log(arrayFruits);
console.log(``);
console.log(`4.Add element or insert an element 'Pineapple' at the last position.`);
var char =arrayFruits.push("Pineapple");
console.log(arrayFruits);
console.log(``);
console.log(`5.Insert an element-'Dragon Fruit' before "Water Melon"`);
arrayFruits.splice(4,0,"Dragon Fruit");
console.log(arrayFruits);
console.log(``);
console.log(`6.Replace an element 'Orange' with 'Kiwi'`);
arrayFruits[2]="Kiwi";
console.log(arrayFruits);
console.log(``);
console.log(`7.Log the elements starting from index 1 to 4`);
var fruit=arrayFruits.slice(1,4);
console.log(fruit);
console.log(``);
console.log(`8.Only select last 3 element and log on console:Use the length property`);
var last=arrayFruits.slice(-3);
console.log(last);
    
